# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MATA56 - Paradigmas de Linguagens de Programação (UFBA)
email: rodrigo@dcc.ufba.br
description: > # this means to ignore newlines until "baseurl:"
  Material da disciplina MATA56 - Paradigmas de Linguagens de Programação,
  professor Rodrigo Rocha Gomes e Souza, Universidade Federal da Bahia (UFBA).
baseurl: "/mata56" # the subpath of your site, e.g. /blog
url: "https://rodrigorgs.github.io/" # the base hostname & protocol for your site
twitter_username: xrodrigorgs
github_username:  rodrigorgs

# Build settings
markdown: kramdown